import { RandomCategory } from './db/models/RandomEvent';

export interface RandomCategoryMeta {
  category: RandomCategory;
  icon: string;
  label: string;
  description: string;
}

export const RANDOM_CATEGORIES: RandomCategoryMeta[] = [
  {
    category: 'questions',
    icon: '💬',
    label: 'Câu hỏi tình yêu',
    description: 'Khám phá nhau qua những câu hỏi thú vị',
  },
  {
    category: 'snap',
    icon: '📸',
    label: 'Thử thách ảnh',
    description: 'Chụp ảnh theo gợi ý ngẫu nhiên',
  },
  {
    category: 'today',
    icon: '🌟',
    label: 'Hôm nay của bạn',
    description: 'Kể về ngày hôm nay của bạn',
  },
  {
    category: 'food',
    icon: '🍜',
    label: 'Ăn gì hôm nay?',
    description: 'Gợi ý món ăn cho cả hai',
  },
  {
    category: 'universe',
    icon: '🌌',
    label: 'Vũ trụ nói gì',
    description: 'Lời nhắn từ vũ trụ dành cho đôi bạn',
  },
];

export const RANDOM_PROMPTS: Record<RandomCategory, Array<{ prompt: string; detail?: string }>> = {
  questions: [
    { prompt: 'Kỷ niệm đáng nhớ nhất của bạn với người ấy là gì?', detail: 'Hãy kể chi tiết nhé!' },
    { prompt: 'Nếu được đi du lịch cùng nhau, bạn muốn đến đâu?', detail: 'Chia sẻ lý do tại sao bạn chọn nơi đó' },
    { prompt: 'Điều gì ở người ấy khiến bạn ngưỡng mộ nhất?', detail: 'Hãy thành thật và cụ thể nhé' },
    { prompt: 'Bữa tối lãng mạn mơ ước của bạn trông như thế nào?', detail: 'Địa điểm, món ăn, không gian...' },
    { prompt: 'Bạn thích nhất khi làm gì cùng nhau?', detail: 'Hoạt động, sở thích chung...' },
    { prompt: 'Khi bạn buồn, người ấy thường làm gì để bạn cảm thấy tốt hơn?', detail: 'Chia sẻ cảm xúc của bạn' },
    { prompt: 'Bạn ước mơ sẽ làm điều gì cùng người ấy trong 5 năm tới?', detail: 'Kế hoạch tương lai của các bạn' },
    { prompt: 'Điều gì khiến bạn cười nhiều nhất khi ở cạnh người ấy?', detail: 'Hãy kể câu chuyện buồn cười nhé' },
    { prompt: 'Bạn đã học được gì từ mối quan hệ này?', detail: 'Những bài học quý giá' },
    { prompt: 'Khoảnh khắc nào bạn cảm thấy yêu người ấy nhiều nhất?', detail: 'Khoảnh khắc bình thường hay đặc biệt?' },
    { prompt: 'Nếu hôm nay là ngày cuối cùng, bạn muốn nói gì với người ấy?', detail: 'Hãy can đảm nói ra nhé' },
    { prompt: 'Bạn mô tả tình yêu của mình bằng một màu sắc?', detail: 'Và tại sao lại là màu đó?' },
    { prompt: 'Bài hát nào gợi nhớ cho bạn về người ấy?', detail: 'Hãy chia sẻ bài hát và lý do' },
    { prompt: 'Điều nhỏ nhặt nào người ấy làm khiến bạn hạnh phúc?', detail: 'Đôi khi điều nhỏ lại có ý nghĩa lớn' },
    { prompt: 'Bạn muốn người ấy biết điều gì mà chưa dám nói?', detail: 'Đây là cơ hội để bày tỏ' },
    { prompt: 'Nếu bạn là một cuốn sách, người ấy sẽ là chương nào?', detail: 'Hãy giải thích sự so sánh của bạn' },
    { prompt: 'Truyền thống hoặc thói quen nào bạn muốn tạo ra cùng người ấy?', detail: 'Hàng tuần, hàng tháng, hàng năm...' },
    { prompt: 'Khi xa nhau, bạn nhớ gì nhất về người ấy?', detail: 'Mùi hương, nụ cười, giọng nói...' },
    { prompt: 'Điều gì khiến mối quan hệ của bạn trở nên đặc biệt?', detail: 'So với những mối quan hệ khác' },
    { prompt: 'Bạn muốn có thêm những trải nghiệm gì với người ấy?', detail: 'Những điều chưa làm nhưng muốn thử' },
  ],
  snap: [
    { prompt: 'Chụp ảnh bầu trời ngay lúc này', detail: 'Dù nắng hay mưa, hãy capture khoảnh khắc này' },
    { prompt: 'Chụp ảnh đôi tay của bạn', detail: 'Đôi tay nói lên rất nhiều điều' },
    { prompt: 'Chụp ảnh góc yêu thích trong phòng', detail: 'Nơi bạn thường ngồi thư giãn' },
    { prompt: 'Chụp ảnh món đồ mang lại may mắn cho bạn', detail: 'Vật kỷ niệm, phụ kiện, hoặc bất cứ thứ gì' },
    { prompt: 'Chụp ảnh selfie với nụ cười thật tươi', detail: 'Không cần filter, hãy tự nhiên nhé!' },
    { prompt: 'Chụp ảnh khung cảnh ngoài cửa sổ', detail: 'Thế giới bên ngoài từ góc nhìn của bạn' },
    { prompt: 'Chụp ảnh thứ màu đỏ gần bạn nhất', detail: 'Tìm kiếm màu của tình yêu xung quanh' },
    { prompt: 'Chụp ảnh nơi bạn đang ngồi', detail: 'Bối cảnh của khoảnh khắc này' },
    { prompt: 'Chụp ảnh đồ uống của bạn lúc này', detail: 'Cà phê, trà, hay nước lọc?' },
    { prompt: 'Chụp ảnh bóng của bạn', detail: 'Hãy sáng tạo với bóng nắng' },
    { prompt: 'Chụp ảnh thứ đang làm bạn cười', detail: 'Chia sẻ nụ cười với người ấy' },
    { prompt: 'Chụp ảnh đôi giày bạn đang đi', detail: 'Đôi giày kể câu chuyện của ngày hôm nay' },
    { prompt: 'Chụp ảnh món ăn/đồ uống bạn vừa có', detail: 'Food photography thôi nào!' },
    { prompt: 'Chụp ảnh biểu cảm khuôn mặt lúc này', detail: 'Honest feeling, no filter' },
    { prompt: 'Chụp ảnh thứ bạn đang đọc/xem', detail: 'Sách, điện thoại, hay TV?' },
  ],
  today: [
    { prompt: 'Hôm nay bạn đã ăn gì ngon nhất?', detail: 'Kể về bữa ăn đặc biệt của ngày' },
    { prompt: 'Điều tuyệt vời nhất xảy ra hôm nay là gì?', detail: 'Dù nhỏ hay lớn, hãy chia sẻ' },
    { prompt: 'Hôm nay bạn cảm thấy thế nào?', detail: 'Thành thật về cảm xúc của bạn' },
    { prompt: 'Bạn đã học được gì mới hôm nay?', detail: 'Kiến thức, kỹ năng, hay bài học cuộc sống' },
    { prompt: 'Người nào khiến bạn vui nhất hôm nay?', detail: 'Và họ đã làm gì?' },
    { prompt: 'Thời tiết hôm nay ảnh hưởng đến tâm trạng bạn thế nào?', detail: 'Nắng, mưa, hay mây mù?' },
    { prompt: 'Bạn đã hoàn thành được điều gì hôm nay?', detail: 'Dù nhỏ cũng đáng tự hào' },
    { prompt: 'Có điều gì khiến bạn stress hôm nay không?', detail: 'Chia sẻ để cảm thấy nhẹ hơn' },
    { prompt: 'Bài hát nào bạn đã nghe nhiều nhất hôm nay?', detail: 'Và cảm xúc khi nghe bài đó?' },
    { prompt: 'Hôm nay bạn mặc gì? Mô tả outfit của bạn', detail: 'Thời trang của ngày hôm nay' },
    { prompt: 'Bạn đã nghĩ đến người ấy vào lúc nào hôm nay?', detail: 'Khoảnh khắc đó như thế nào?' },
    { prompt: 'Nếu hôm nay là một màu, nó sẽ là màu gì?', detail: 'Và tại sao?' },
    { prompt: 'Bạn đã giúp đỡ ai hôm nay chưa?', detail: 'Một hành động tử tế nhỏ thôi' },
    { prompt: 'Điều bạn mong chờ nhất cho ngày mai?', detail: 'Kế hoạch hay hy vọng gì?' },
    { prompt: 'Bạn đã tự thưởng cho mình điều gì hôm nay?', detail: 'Vì đã cố gắng hết sức' },
  ],
  food: [
    { prompt: 'Thử nấu món bánh xèo tối nay nhé!', detail: 'Công thức: bột gạo, tôm, thịt, giá đỗ, hành lá. Ăn kèm rau sống và nước chấm' },
    { prompt: 'Hôm nay ăn phở đi!', detail: 'Phở bò hay phở gà? Thêm hành gừng, tương hoisin và tương ớt' },
    { prompt: 'Thử làm salad trái cây cùng nhau', detail: 'Dưa hấu, dứa, xoài, dâu tây, thêm chút mật ong và bạc hà' },
    { prompt: 'Bánh mì Việt Nam cho bữa sáng!', detail: 'Bánh mì giòn với pate, chả, rau thơm và tương ớt' },
    { prompt: 'Bún bò Huế - đậm đà và cay nồng', detail: 'Nước dùng sả ớt, bún, giò heo, chả cua. Ăn kèm rau thơm' },
    { prompt: 'Lẩu thái cho buổi tối lãng mạn', detail: 'Nước dùng chua cay, hải sản tươi, rau xanh, nấm. Ngồi ăn cùng nhau thật ấm cúng' },
    { prompt: 'Cơm rang dưa bò - nhanh và ngon', detail: 'Cơm nguội, dưa cải, thịt bò, trứng, tỏi phi. Đơn giản nhưng đậm đà' },
    { prompt: 'Bánh cuốn Hà Nội cho buổi sáng thư giãn', detail: 'Bánh mỏng nhân thịt nấm mộc nhĩ, chấm nước mắm chua ngọt' },
    { prompt: 'Gỏi cuốn tôm thịt - thanh mát', detail: 'Bánh tráng cuộn tôm, thịt, bún, rau thơm. Chấm tương hoisin đậu phộng' },
    { prompt: 'Bơ sữa dừa - món tráng miệng đặc biệt', detail: 'Bơ chín, đường, sữa đặc, nước cốt dừa. Để tủ lạnh 30 phút rồi thưởng thức' },
    { prompt: 'Đặt pizza chia sẻ cùng nhau tối nay', detail: 'Chọn topping yêu thích của cả hai, ăn kèm nước ngọt và phim hay' },
    { prompt: 'Chè khúc bạch - mát lạnh ngọt ngào', detail: 'Hạnh nhân, nước cốt dừa, trái cây tươi. Hoàn hảo cho ngày nắng' },
    { prompt: 'Mì Ý sốt cà chua - lãng mạn kiểu Ý', detail: 'Spaghetti, thịt bò băm, cà chua, tỏi, oregano. Rắc phô mai parmesan' },
    { prompt: 'Súp bí đỏ ấm áp cho buổi tối mưa', detail: 'Bí đỏ, hành tây, tỏi, kem tươi. Xay nhuyễn, ăn với bánh mì nướng' },
    { prompt: 'Thạch sương sáo dừa non giải nhiệt', detail: 'Thạch sương sáo, nước cốt dừa, đường, đá viên. Thanh mát tức thì' },
  ],
  universe: [
    { prompt: 'Vũ trụ nói: Hôm nay hãy gửi một tin nhắn thật ngọt ngào cho người ấy 💝', detail: 'Đừng ngần ngại, tình yêu cần được nói ra' },
    { prompt: 'Năng lượng hôm nay: ☀️ Tích cực và tràn đầy yêu thương', detail: 'Hãy lan tỏa năng lượng này đến người ấy' },
    { prompt: 'Vũ trụ thì thầm: Hãy nhớ lại kỷ niệm đẹp nhất của hai bạn 🌟', detail: 'Chia sẻ kỷ niệm đó với người ấy hôm nay' },
    { prompt: 'Lời tiên tri: Một bất ngờ dễ thương đang chờ bạn 🎁', detail: 'Có thể là từ người ấy, có thể là từ cuộc sống' },
    { prompt: 'Vũ trụ gợi ý: Hãy làm một điều bất ngờ cho người ấy hôm nay 🎊', detail: 'Nhỏ thôi nhưng chân thành' },
    { prompt: 'Thông điệp từ các vì sao: Tình yêu của các bạn rất đặc biệt ✨', detail: 'Hãy trân trọng và chăm sóc nó mỗi ngày' },
    { prompt: 'Vũ trụ nhắc nhở: Đừng quên nói "em yêu anh/anh yêu em" hôm nay ❤️', detail: 'Ba từ đơn giản nhưng có sức mạnh vô cùng lớn' },
    { prompt: 'Năng lượng ngày hôm nay: 🌈 Đầy màu sắc và hạnh phúc', detail: 'Chia sẻ niềm vui này với người ấy' },
    { prompt: 'Vũ trụ dự báo: Buổi tối hôm nay sẽ rất ấm áp 🕯️', detail: 'Hãy dành thời gian quality time cùng nhau' },
    { prompt: 'Lời khuyên từ thiên hà: Hãy lắng nghe người ấy nhiều hơn hôm nay 👂', detail: 'Đôi khi chỉ cần ai đó lắng nghe là đủ' },
    { prompt: 'Vũ trụ thì thầm: Hãy chụp ảnh selfie cùng nhau hôm nay 📸', detail: 'Lưu giữ khoảnh khắc này cho tương lai' },
    { prompt: 'Thông điệp yêu thương: Tình yêu không cần lý do, chỉ cần trái tim 💗', detail: 'Hãy yêu một cách tự do và chân thành' },
    { prompt: 'Vũ trụ báo: Hôm nay là ngày tốt để bắt đầu một truyền thống mới 🌙', detail: 'Một thói quen nhỏ có thể tạo nên kỷ niệm đẹp' },
    { prompt: 'Năng lượng tích cực: Hãy cùng nhau mơ về tương lai 🔮', detail: 'Những giấc mơ chung gắn kết hai người lại' },
    { prompt: 'Vũ trụ kết nối: Dù xa nhau, trái tim luôn cùng nhịp đập 💞', detail: 'Tình yêu vượt qua mọi khoảng cách' },
    { prompt: 'Lời tiên tri ngọt ngào: Nụ cười của người ấy sẽ là điều đẹp nhất bạn thấy hôm nay 😊', detail: 'Hãy làm mọi thứ để mang lại nụ cười đó' },
    { prompt: 'Vũ trụ nhắn gửi: Hãy nấu một bữa ăn đặc biệt tối nay 🍽️', detail: 'Bữa ăn tự tay nấu luôn ngon hơn' },
    { prompt: 'Thông điệp từ ngôi sao: Hãy viết một bức thư tay cho người ấy 📝', detail: 'Trong thời đại số, một bức thư tay rất đặc biệt' },
    { prompt: 'Vũ trụ gợi ý: Nghe nhạc cùng nhau qua điện thoại tối nay 🎵', detail: 'Cùng nghe một bài, dù ở xa cũng như gần' },
    { prompt: 'Năng lượng hôm nay: 🌺 Nồng ấm và dịu dàng như mùa xuân', detail: 'Hãy là mùa xuân trong cuộc đời nhau' },
  ],
};
